### ISSUE TITLE
Entity ID Configuration Value

### ISSUE THREAD

**Issue by mattfirtion** [bitium/confluence-saml-plugin#13]
Should the value in the 'Entity ID' box match the entity ID of the SP when configured in the authentication provider?  If so, there is a bug with how the entity ID field is used.  The entity ID is always returned as public String getSpEntityId() { defaultBaseURL + "/" getAlias()  where getAlias returns confluenceSAML

```
public String getAlias() {
		return "confluenceSAML";
	}

	public String getBaseUrl() {
		return StringUtils.defaultString(defaultBaseURL);
	}

	public String getSpEntityId() {
		return defaultBaseURL + "/" + getAlias();
	}
```

**Comment by goosetav** [comment]
hi @mattfirtion, assuming you're referring to the config screen inside Confluence, the value in the "Entity ID box" is the value passed from the IdP to the SP (i.e. Confluence).

The `getSpEntityId` call is the EntityID of confluence itself and thus is actually static

LMK if that makes sense
