### ISSUE TITLE
Unable to edit SAML Endpoint value in Confluence Plugin

### ISSUE THREAD

**Issue by rkadam** [bitium/confluence-saml-plugin#14]
Hi there,

I'm unable to enter correct value for SAML Endpoint as this field is "disabled" (read only). Attached is screenshot to give visual:
<img width="580" alt="screen shot 2015-08-04 at 2 06 25 pm" src="https://cloud.githubusercontent.com/assets/1423996/9072834/60575c4a-3ab2-11e5-9b79-9eabce7edbae.png">

I'm able to update all other values except SAML Endpoint. Could you please guide, how can I update this value?

Thank you for your time

**Comment by goosetav** [comment]
@rkadam what value are you trying to update it to? this value is fixed for the Confluence side and is meant to be copied into your Identity Provider

**Comment by rkadam** [comment]
Erik -- Thanks for quick update. I was under impression that I need to copy SAML Endpoint value from Identity Provider. But it seems to be other way round right? I will ask them to use this value.

Thanks,
Rajendra

**Comment by goosetav** [comment]
Rajenda - correct, you copy the value over to the identity provider. If it helps, we have a support article for integrating Confluence into the Identity Provider we make: https://support.bitium.com/customer/portal/articles/1643287-configuring-saml-for-confluence-on-prem?b_id=4928
