### ISSUE TITLE
OneLogin SSO integration - SAML plugin internal error

### ISSUE THREAD

**Issue by rkadam** [bitium/confluence-saml-plugin#15]
Erik -- Thank you very much for your help with earlier ticket.

We are trying to achieve SSO with OneLogin as IdP. We've updated SAML endpoint as suggested by you. But now when I click on Confluence link from OneLogin, it throws *SAML plugin internal error*.

Log indicates following details:

```
2015-08-05 12:40:01,765 ERROR [ajp-bio-6081-exec-5] [bitium.confluence.servlet.SsoLoginServlet] doPost saml plugin error + Metadata for issuer https://app.onelogin.com/saml/metadata/466134 wasn't found
 -- referer: https://xxx.onelogin.com/client/apps/select/58684010 | url: /plugins/servlet/saml/auth | userName: anonymous
```

Any idea what might be going on wrong here? Not sure what Metadata plugin is not able to find. Is there anyway, we can get more debugging information.

Thank you again for all your help.
Rajendra

P.S: If I use my credentials to directly login using traditional Confluence Login Screen, Onelogin does able to detect that I'm already logged in. But only when I try to login by clicking on *Wiki* link from OneLogin, I get above error.

**Comment by goosetav** [comment]
@rkadam hmmm ... seems like something isn't being sent back from OneLogin. Can you try using https://addons.mozilla.org/en-us/firefox/addon/saml-tracer/ to get a copy of the SAMLResponse that is being POST'd to Confluence?

**Comment by rkadam** [comment]
Sure Erik. Let me find out.

**Comment by rkadam** [comment]
Erik -- attached are two SAML Tracer reports using addon you mentioned.

[SAML Tracer Report 1](https://drive.google.com/file/d/0BzyXGbRlvmbSTUppM2RZTWdlREU/view?usp=sharing)
[SAML Tracer Report 2](https://drive.google.com/file/d/0BzyXGbRlvmbScXNzdVJDZGxGbTA/view?usp=sharing)

Couple of things I've noticed is, 
* SAML endpoint mentions SSL port like https://wiki.company.com:443/..., it may not be necessary. simple URL https://wiki.company.com/ should work. (though this shouldn't be problem here.)
* When error is thrown, URL in browser is like this `https://wiki.company.com/confluence/login.action?samlerror=plugin_exception` But we already have confluence mapped to our main domain, so URL should be `https://wiki.company.com/login.action?samlerror=plugin_exeception` Not sure if this is a problem or not, but worth noting.

Let me know if you find anything interesting from SAML Tracer reports.

Thank you,
Rajendra

**Comment by rkadam** [comment]
Here is [another SAML Tracer report](https://drive.google.com/file/d/0BzyXGbRlvmbScmtVbG1uRUNUdEU/view?usp=sharing) in case it provides better sampling. Thanks again.

**Comment by adhisun** [comment]
Note sure whether audience/EntityID is the issue: We received https://dns:443/confluenceSAML as the audience in the SAML Request and then used it in our config. It helps to resolve the SAML Plugin error.

**Comment by rkadam** [comment]
Adi -- do you need any additional information? Sorry didn't understood your comment.

**Comment by adhisun** [comment]
Hello

No. I am not from the support team. I am just a visitor to this site and
noticed that you faced the same error message as I did.


*Adi Sundaram*



Tel: (Off) 510-713-5285
Email: adi@logitech.com

**Comment by rkadam** [comment]
Adi -- Thanks for clarification. Are you folks also doing integration for OneLogin? with Confluence?

**Comment by adhisun** [comment]
No. We are doing Confluence with a different IdP.


*Adi Sundaram*



Tel: (Off) 510-713-5285
Email: adi@logitech.com

**Comment by rkadam** [comment]
Adi -- Thank you for details. Erik -- has been kind and helping us with debugging. Hoping we will get resolution soon.

**Comment by gammalyrae** [comment]
Hello Rajendra,

 I was not able to reproduce your scenario.
  can you may be share the exact configuration details both for Confluence SAML plugin and OneLogin? Where is this wiki link in OneLogin, which results in an error?

You can send screenshots directly to me: nerijus.areska@gmail.com. I will try to reproduce it with OneLogin.

Thanks,
Nerijus

**Comment by rkadam** [comment]
Big thanks to Nerijus and Erik, we have this working on our DEV instance. Will continue testing it to make sure we have all our scenarios working using this integration setup.

cheers guys,
Raju

**Comment by brucedyoung** [comment]
I'm having the same problem.
Not using OneLogin as IdP, but get same error
"doPost saml plugin error + Metadata for issuer https://app.onelogin.com/saml/metadata/466134 wasn't found"

Can you post what you did to fix?

thanks
Bruce

**Comment by rkadam** [comment]
Bruce -- 
* I'm not sure how you can get this error if you are not using OneLogin as a IdP.
* In our case it was mainly a configuration issue. What we found out was on Wiki side, SAML Endpoint URL should include port number on which it's listening. And other URL such as Login URL, Entity ID should be without port numbers!

Hope this helps,
Raju

**Comment by brucedyoung** [comment]
I'm sorry, you are right rkadam,
I was trying to use https://www.testshib.org/
I register the hand-built SP metadata file
Entered https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO as the Login URL in the plugin
It successfully authenticates at https://idp.testshib.org/idp/Authn/UserPassword
Then I get the "SAML plugin internal error" and 
"doPost saml plugin error + Metadata for issuer https://idp.testshib.org/idp/shibboleth wasn't found"

I suspect I need to include the IdP metadata location in the SP metadata file?

thanks
Bruce

**Comment by rkadam** [comment]
I'm not very sure Bruce. Sorry!

**Comment by goosetav** [comment]
@brucedyoung can you open another ticket that is specific to your IdP? thanks

**Comment by mkattie** [comment]
We are using SecureAuth as IDP and I am seeing the error "Metadata for issuer https://... not found". Does the plugin try to download the metadata xml from IDP?
