### ISSUE TITLE
SAML 20. JIRA  plugin

### ISSUE THREAD

**Issue by jimsaxton** [bitium/confluence-saml-plugin#16]
Hey,
I have installed the JIRA / SAML 2.0 plugin into JIRA 6.3.3.as a means of SSO to our user repository (webseal).  I have added the meta-data from the idp, where do I grab the metadata from the pluging / jira to add to the idp?   OR,  look at it this way, I added all the meta-data from the IDP to the plugin, but I am getting a 403 (forbidden) due to missing metadata from the plugin to the user repository.
Is there documentation to extract he meta-data from the saml plugin / jira to provide to the IDP?

**Comment by goosetav** [comment]
closing in favor of bitium/jira-saml-plugin#6
