### ISSUE TITLE
How to integrate SAML on-top of AD to use this plugin

### ISSUE THREAD

**Issue by seanlon11** [bitium/confluence-saml-plugin#17]
I'm new to SAML, so this is probably a dumb question: is there a way for a SAML IDP to integrate with Microsoft AD?  We currently use a bastardized version of Seraph for SSO into Jira (using Kerberos), but we would love to use this plugin instead if it fits our bill.  I've run through some google search results, but the more I read the more I get the feeling of "I don't know what I don't know" in regards to SAML. 

So maybe this is not the right place to ask, but since I can barely spell SAML and am interested in your plugin, I thought maybe you could point me in the right direction on if/how I can use SAML and Microsoft AD to utilize this plugin. 

Thanks, 
     Sean

**Comment by goosetav** [comment]
hi @seanlon11 -- yep, most commercial SAML IdP's will integrate with AD.

You can sign up for a demo account of the IdP we provide at https://www.bitium.com if you want to see it in action.
