### ISSUE TITLE
Configured .. but ends in Login page

### ISSUE THREAD

**Issue by adhisun** [bitium/confluence-saml-plugin#18]
Hello

I configured our Confluence with this Plugin. Our IDP is Salesforce Identity.

When we access the application using the IDP or SP intiated, we always end in the login page.

We pass username as  Name ID attribute in the Subject. 

Could you please check if there are any other config we need to check.

**Comment by goosetav** [comment]
Hi @adhisun are you getting any errors in the confluence logs?

**Comment by adhisun** [comment]
No Errorrs. I just shows the login page.

On Tuesday, August 25, 2015, Erik Gustavson <notifications@github.com>
wrote:

> Hi @adhisun <https://github.com/adhisun> are you getting any errors in
> the confluence logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitium/confluence-saml-plugin/issues/18#issuecomment-134831479>
> .
>


-- 
Sent from iPhone

**Comment by goosetav** [comment]
@adhisun we have docs for using Bitium's IdP with the plugin at https://support.bitium.com/customer/en/portal/articles/1643287-configuring-saml-for-confluence-on-prem?b_id=4928 -- perhaps these can point you in the right direction for using Salesforce's IdP?

if that doesn't help, can you try using the Firefox extension https://addons.mozilla.org/en-us/firefox/addon/saml-tracer/ to trace the SAML process?

**Comment by adhisun** [comment]
We had enabled crowd and that caused the issue. Disabling the crowd sso resolved the issue.  

Is there any backdoor entry for admin users or local directory users, after we enable force SSO ?

**Comment by goosetav** [comment]
hi @adhisun there aren't any backdoor entries after "force SSO" is enabled
