### ISSUE TITLE
Failed to execute goal on project SAML2PluginJira

### ISSUE THREAD

**Issue by srinivaspatruni** [bitium/confluence-saml-plugin#19]
I tried to configure in my eclipse but i got the below error

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project SAML2PluginJira: Could not resolve dependencies for project com.bitium.jira:SAML2PluginJir
a:atlassian-plugin:1.0.1: Failure to find com.bitium.saml:SAML2Commons:jar:1.0 in https://maven.atlassian.com/repository/public was cached in the local repository, resolution will
not be reattempted until the update interval of atlassian-public has elapsed or updates are forced

**Comment by goosetav** [comment]
hi @srinivaspatruni have you installed the SAML2Commons lib locally? see https://github.com/bitium/confluence-saml-plugin#install-the-atlassian-saml-commons
