### ISSUE TITLE
Landing page should be "SITE Home page" and not dashboard.action

### ISSUE THREAD

**Issue by rkadam** [bitium/confluence-saml-plugin#20]
Very first thank you for making this Connector available. We are almost ready for Production push. There is one tiny but important thing I've noticed. After successful login, user is directed to Dashboard.action. 

In our case though, we want user to land on our own Default Wiki space. This is done by setting value for [Confluence Site Home Page](https://confluence.atlassian.com/doc/configuring-the-site-home-page-138140.html) So when user logs in directly using Confluence authentication, they are directed to this Site Home Page.

Is there any way we can configure Connector so that it will redirect users coming from OneLogin to our Site home page?

Let me know if you need any other information. Thanks for all your help.
Raju

**Comment by rkadam** [comment]
After going through code, I found that right now Plugin assumes it need to redirect to dashboard.action

```
-- Source: SSOLoginServlet.java
		        if (result) {
		        	response.sendRedirect("/confluence/dashboard.action");
		        	return;
		        }
```

It will be really helpful if users can 
* Configure this "Redirection" value from SAML Plugin configuration.
* Or if Plugin can pickup the value that's set as a [Confluence Site Home Page](https://confluence.atlassian.com/display/DOC/Configuring+the+Site+Home+Page) under *Further Configuration* section in Confluence Global Configuration screen.

**Comment by rkadam** [comment]
* I'm also checking with Atlassian to find out if we can access value of SITE Home page via APIs. If that's option available, we can use API to get site home page value and set it here for redirection.
* Will update again as I've more information.

**Comment by rkadam** [comment]
* Atlassian Support says this is *out of scope* :-(
* I've raised this question @ AAC. Let's hope if we get any answers: https://answers.atlassian.com/questions/25691421/accessing-confluence-site-homepage-value-via-rest-api-

**Comment by rkadam** [comment]
Got workaround solution suggested on [AAC](https://answers.atlassian.com/questions/25691421) We will need to add another configuration parameter to set this value though through "Configure" section of SAML Connector.

Will see if I can do that here by myself!

**Comment by rkadam** [comment]
Good news!

I've success in getting what we want. I've tested it locally by changing snippet I've mentioned above to redirect it to "/display/<SPACEKEY>". And it works. After user logs in, they are re-directed to wiki space instead of Dashboard.

Now next course of action is to make this configurable via Plugin configure section so that we don't have to hardcode any of the values. It will require some reading on my side to understand how latest Confluence Plugin are developed. But shouldn't be hard. I believe I need to update SAMLConfluenceConfig.java and/or ConfigureAction.java.

@goosetav let me know if my understanding is correct and I'm going in right direction. Thanks.

**Comment by rkadam** [comment]
Nerijus -- Thank you very much for starting on this feature request. Will test changes once they are available in main branch.

cheers,
Raju

**Comment by goosetav** [comment]
@rkadam can you test the new change? If it works for you I will update the official plugin.

**Comment by rkadam** [comment]
* Yes I've tested it on our DEV instance and seems to be working just fine as I thought. Will do more through test once these changes are available in official plugin.
* One thing I noticed is Nerijus made changes on 1.0.1 branch and main branch is on 1.0.2. Hoping we will move only changes done for these feature into main branch.

**Comment by rkadam** [comment]
Hey Guys -- Do let me know when changes will be available in main branch and I will start testing immediately. Thank you!

**Comment by rkadam** [comment]
@gammalyrae Good Morning!
Wanted to check with you and see if when we can have Confluence SAML Plugin newer version available with changes that you have made in a branch. Let me know if I can be any help here.

Thank you,
Raju

**Comment by peter-hanraets** [comment]
Hi Instead of trying to read the defined homepage couldn't you just go to the site root, and have Confluence figure out where to go next?

**Comment by rkadam** [comment]
Peter -- 

* You are right by setting "/", Confluence does figure out how to redirect user to Site Home page. I myself tested this successfully.
* With this new configuration parameter, it just makes life easy to redirect user to different landing page (other than SITE homepage) if necessary.

Thank you for your feedback.

**Comment by rkadam** [comment]
Addition of **Redirect URL** parameter and suggestion by Peter on setting _/_ we are all set here. Thank you everyone for all your help to resolve this issue.
