### ISSUE TITLE
Unable to compile and run plugin

### ISSUE THREAD

**Issue by rkadam** [bitium/confluence-saml-plugin#21]
I'm following steps mentioned  [plugin documentation](https://github.com/bitium/confluence-saml-plugin) for development setup. But running into this error after executing *atlas-run* command:
```
[ERROR] Failed to execute goal com.atlassian.maven.plugins:maven-amps-dispatcher-plugin:5.1.6:run (default-cli) on project SAML2Commons: Couldn't detect an AMPS product to dispatch to -> [Help 1]
```

Possible causes are:

1. ~~I'm not running atlas-run in source directory.~~ Not true, I'm already in correct source directory.
2. May be some of packages required are not installed. Reference [JIRA DVCS Connect] (https://jira.atlassian.com/browse/DCON-505)

Not sure how to verify this last probable cause. Any help here will be really appreciated.

**Comment by goosetav** [comment]
@rkadam were you able to install the SAMLCommons project? Your project layout should look like:

```
<your projects>
   /confluence-saml-plugin
   /atlassian-saml
```

and after running `mvn clean install` in the `/atlassian-saml` project, you should be able to find the distribution in your `~/.m2` directory:

```
~ # cd  ~/.m2/repository/com/bitium/saml/SAML2Commons/1.0/
~/.m2/repository/com/bitium/saml/SAML2Commons/1.0 # ls -l
total 20K
-rw-r--r-- 1 xxxx yyyy  12K Aug  1 12:06 SAML2Commons-1.0.jar
-rw-r--r-- 1 xxxx yyyy 3.5K Aug  1 12:03 SAML2Commons-1.0.pom
-rw-r--r-- 1 xxxx yyyy  179 Aug  1 12:06 _remote.repositories
```

**Comment by rkadam** [comment]
Erik -- Your answer help me solve the problem. Thanks! 

Till now I had installed SAMLCommons project and was trying to atlas-run from there itself. After reading your layout structure, realized that I still need to git clone SAML Plugin. Git clone and atlas-run, and I'm able to access Confluence now!

But one thing I'm not able to figure out is why I don't see SAML plugin in User installed Add-on. Isn't it should be by default installed? or I've to install manually again?

Thanks again for prompt feedback.
Raju

**Comment by goosetav** [comment]
glad to help Raju

when I use `atlas-run` the plugin does get installed by default but I always need to search for "saml" in "all plugins" in order to see it.

**Comment by rkadam** [comment]
True. Plugin is installed, but not under "User installed" rather "System installed". Thank you for all your help Erik!
