### ISSUE TITLE
Will this add-in be available for Confluence Cloud?

### ISSUE THREAD

**Issue by chrisp1992** [bitium/confluence-saml-plugin#22]
We would like to use this plugin, however it seems that there is not a version of it for the Cloud instance. Are there any plans for this to be added to the Marketplace for the cloud environment?

Thanks

**Comment by goosetav** [comment]
Unfortunately Atlassian doesn't provide the necessary API's for the plugin to work in Atlassian Cloud. IMHO they should support SAML but they seems unwilling: https://jira.atlassian.com/browse/ID-80
