### ISSUE TITLE
Metadata for Shibboleth IDP - SAML 2.0 Single Sign-On for Jira

### ISSUE THREAD

**Issue by jerrykurian** [bitium/confluence-saml-plugin#24]
Thanks for the great plugin.
I am trying to set it up to work with shibboleth ipd version 3. 
Shibboleth needs a metadata to be specified and i didn't find a way to get a metadata. I have tried working with existing sample metadatas and making changes, but it dosnt seem to work.
I am trying out the JIRA plugin, but strangely, i get the following error message
 No metadata returned for http://jira.assessrite.com:80/confluenceSAML in role {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor with protocol urn:oasis:names:tc:SAML:2.0:protocol

Would appreciate any help,

**Comment by marconett** [comment]
I'm having similar problems trying to get LemonLDAP to work. Did you come up with working metadata?

**Comment by goosetav** [comment]
closing in favor of #41
