### ISSUE TITLE
Confluence SAML2Plugin with ADFS Difficulties

### ISSUE THREAD

**Issue by leewilmott** [bitium/confluence-saml-plugin#28]
I am trying to get SAML2Plugin for Confluence working with ADFS 3.0 on Windows Server 2012 R2.

My Confluence server is named 'conftest.mydomain.com' (domain name has been renamed).

I cannot find any documentation on how to configure this, so I'm using settings that I have used successfully with other Service Providers.

I have configured the SAML 2.0 Plugin configuration with the following...

    SAML Endpoint: https://conftest.mydomain.com:443/test/plugins/servlet/saml/auth
    Login URL: https://fs.mydomain.com/adfs/ls
    Logout URL: <empty>
    X.509 Certificate: ----- BEGIN CERT.....etc...etc...
    Entity ID: http://fs.mydomain.com/adfs/services/trust

The confluence log file reads...

    2015-10-14 16:21:05,622 ERROR [ajp-bio-8090-exec-11] [bitium.confluence.servlet.SsoLoginServlet] doPost saml plugin error + Response doesn't have any valid assertion which would pass subject validation
    -- referer: https://fs.mydomain.com/adfs/ls/wia | url: /test/plugins/servlet/saml/auth | userName: anonymous

I have configured my ADFS with the following...

    Replying Party Identifier: https://conftest.mydomain.com/test/plugins/servlet/saml/auth
    Secure hash algorithm: SHA-256 (but I've tried SHA-1 too)
    Endpoint: Binding: POST.  Trusted URL: https://conftest.mydomain.com/test/plugins/servlet/saml/auth
    Claims: Active Directory SAM-Account-Name -> Name ID

My SAML request can be found here... https://pastebin.com/jeXF9PQk.

Is anyone able to help me?

Thanks in advance.

Kind regards,

Lee

**Comment by thnetila** [comment]
I use AD FS with this plug-in. SHA-256 works for me. I had a similar problem. It was caused by wrong certificate.

Check if you use correct X.509 Certificate. It must be a AD FS signing certificate. You can find it in AD FS Console => Service => Certificates  => Token-signing. Export it as Base-64 encoded.

Your SAML request looks Ok.

**Comment by fredclown** [comment]
I've got the same error in the Confluence logs. Did you ever resolve it? I am indeed using the correct cert, so that's not the issue.
