### ISSUE TITLE
Invalid SAML Endpoint value

### ISSUE THREAD

**Issue by evevlc** [bitium/confluence-saml-plugin#31]
After installing the plugin and configuring with ADFS 3.0, I noticed that the SAML Endpoint value (which I cannot change) is not correct.
It is listed as this: "http://confluence.mydomain.com:443/plugins/servlet/saml/auth". The server base URL starts with https:// and omits the port 443.
I attached screenshots of both.

ADFS will not allow an endpoint without HTTPS, the only way to configure it was with https, and I am unable to log on. I see this error on the Log in page: "SAML plugin internal error". 

I see this error in the Confluence logs: [bitium.confluence.servlet.SsoLoginServlet] doPost saml plugin error + Intended destination https://confluence.mydomain.com:443/plugins/servlet/saml/auth doesn't match any of the endpoint URLs for profile urn:oasis:names:tc:SAML:2.0:profiles:SSO:browser

I am assuming the problem is caused by the SAML endpoint value being incorrect, but I am unclear as to how to fix this.

Thanks in advance for your help.

![image](https://cloud.githubusercontent.com/assets/15270047/10704103/1eeb3110-799a-11e5-8d34-5a5d3a633aea.png)
----
----
![image](https://cloud.githubusercontent.com/assets/15270047/10704223/f81b8462-799a-11e5-8909-bc59c495641d.png)

**Comment by jimsaxton** [comment]
Hey - in the event you have not tried this ... I ran into this a few times.  This occurred when I installed the plugin when the url was HTTP...  once I changed my base URL to HTTPS, I had to uninstall the plugin and reinstall it.  Once re-installed, the https was picked up properly.
