### ISSUE TITLE
Redirect to called URL

### ISSUE THREAD

**Issue by peter-hanraets** [bitium/confluence-saml-plugin#35]
Currently if a user follows a link into Confluence from an external source (mail, other application), and he/she is not logged in they will, after logging in at the IdP, be redirected to the dashboard or configured redirect URL. Would it not be possible to get the original URL from the login.action page and redirect to that page? That's how it normally works in Confluence, e.g.
User clicks on the following link:

https://devcolla.vanderlande.com/display/WPPP/WPP+Program+Home

Confluence notices user is not logged in and redirects to:

https://devcolla.vanderlande.com/login.action?os_destination=%2Fpages%2Fviewpage.action%3FspaceKey%3DWPPP%26title%3DWPP%2BProgram%2BHome&permissionViolation=true

User logs in and is redirected to:

https://devcolla.vanderlande.com/pages/viewpage.action?spaceKey=WPPP&title=WPP+Program+Home

So if we could read/store the os_destination and redirect to there instead of redirectURL the default behaviour of Confluence would not be affected so much.

**Comment by rkadam** [comment]
SAML plugin is working great for us so far. But we are facing this same issue when user clicks on the link very first time and redirected to OneLogin for SSO authentication.

Luckily it seems problem can be solved if we use this os_destination parameter as part of redirection process. Here are changes I'm proposing:

```
SsoLoginServlet.java

		        if (result) {
		        	String redirectUrl = saml2Config.getRedirectUrl();
		        	if (redirectUrl == null || redirectUrl.equals("")){
		        		redirectUrl = "/confluence/dashboard.action";
		        	}
		        	response.sendRedirect(redirectUrl);
		        	return;
		        }

to 

if(result){
	if(request.getSession().getAttribute("os_destination") != null)
	{
	    String os_destination = 
	        request.getSession().getAttribute("os_destination").toString();
	        response.sendRedirect(os_destination);
	}else{
   		String redirectUrl = saml2Config.getRedirectUrl();
       	if (redirectUrl == null || redirectUrl.equals("")){
       		redirectUrl = "/confluence/dashboard.action";
       	}
       	response.sendRedirect(redirectUrl);
       	return;	
	}     
}
```
This way we will honor os_destination parameter if available (that is if user is coming from specific wiki url) and also redirect users to specific home page if not.

Hope this makes sense! Thank you very much for all the help!

**Comment by rkadam** [comment]
Guys, I've found the fix. With this fix, things are working on our stage
environment exactly as we needed. FYI, changes are more than I mentioned in
my earlier comment.

Will add changes to fork soon. Say tuned.

Happy Friday,
Raju

**Comment by rkadam** [comment]
I've pushed changes into my forked version. It may be silly to ask, but how to send push request so that these changes are available for review and then possible inclusion in main branch here!

**Comment by rkadam** [comment]
@peter-hanraets One request: if possible can you try [Plugin jar available from forked version in my git hub account](https://github.com/rkadam/confluence-saml-plugin/blob/master/SAML2Plugin-1.0.3-Panddora-Snapshot.jar). And let me know if that works for you.

It goes without saying, try this new proposed changes in your Dev / Test environment. Things may not be ready for Production yet. So watch out for falling objects if any!

Thank you for your feedback!
Raju

**Comment by peter-hanraets** [comment]
Hi Raju,

Works like a charm in our acceptance environment. I end up at the correct page and not the homepage (our redirect URL was set to /).

To get your code into the bitium repository you should create a pull request. The owner(s) can then accept that request and pull the code into that repo.

Cheers,
Peter

**Comment by rkadam** [comment]
Awesome! Peter, thanks for confirming. I've already created pull request
for this plugin. Hoping Erik gets time to approve it soon!

Also FYI, similar problem was observed in case of JIRA SSO integration
(issue #23 for jira-saml-plugin I believe). I've given fix there too an
created a pull request.

If you are using JIRA along with SSO, we would be happy to get feedback
there too.

Thanks again for quick feedback.

Happy holidays,
Raju

**Comment by rkadam** [comment]
Quick updates: While we are waiting for our changes to be merged into main branch here, we went ahead with forked branch (plugin branch) and deployed it into Production.

Users seems to be happy :+1: 

Thank you everyone for all your help. Wishing you all a very happy new year!

cheers,
Raju

**Comment by peter-hanraets** [comment]
Same here, installed in production and everything is working fine, better than before.

**Comment by rkadam** [comment]
Peter -- Thanks for updates on your end. Glad it's working for you too! Hoping fix will be part of main branch very soon. @goosetav

**Comment by rkadam** [comment]
@rkarodia We have installed 1.0.5 of Confluence SAML Plugin. But it doesn't seem to contain the fixes for redirection URL that I've mentioned earlier. Can you please confirm if they have been added into main branch?
