### ISSUE TITLE
Development - support for Jira, Bamboo and Stash

### ISSUE THREAD

**Issue by jthomas786** [bitium/confluence-saml-plugin#5]
Hello,

We have a need to integrate our installations of Bamboo, JIRA and Stash as well as Confluience into our SAML 2.0 authentication provider. Would you be available to assist us with this?

Thanks,
Jerry Thomas

**Comment by gjaness** [comment]
I'm also interested in SAML SSO for Jira, Confluence and Stash. Any chance add-ons for Jira and Stash are in development.

**Comment by goosetav** [comment]
@gjaness We do have a Jira add-on in development -- I'll update this thread when we're ready to release it. Are you running Stash and Confluence as stand-alone or are they looking to Jira for their user directory? What IdP are you planning to use?

**Comment by gjaness** [comment]
Hello Eric,

Thanks for the update. Confluence and Stash are using the Jira Directory but we don’t necessarily need to keep that setup for the long term. It was the closest to SSO we had before using an IDP. I’ve talked with Rand Lutomski of Bitium several times but our security team decided we should use Centrify. We rolled it out with a couple SAML apps last week.

Thank you,

Greg Janess
IT Manager
Fitbit, Inc

On Apr 19, 2015, at 09:47, Erik Gustavson <notifications@github.com<mailto:notifications@github.com>> wrote:


@gjaness<https://github.com/gjaness> We do have a Jira add-on in development -- I'll update this thread when we're ready to release it. Are you running Stash and Confluence as stand-alone or are they looking to Jira for their user directory? What IdP are you planning to use?

**Comment by prijst** [comment]
Any updates on JIRA support?

**Comment by goosetav** [comment]
@gjaness and @prijst please see https://github.com/bitium/jira-saml-plugin/releases/tag/1.0.1
