### ISSUE TITLE
Need to delete all values in confluence-saml-plugin

### ISSUE THREAD

**Issue by itamarbs** [bitium/confluence-saml-plugin#6]
Hi
How can I delete the values to start afresh.
the data is kept, although I uninstalled and reinstaled the plugin

Thanks

**Comment by goosetav** [comment]
hi @itamarbs you should be able to look in `config/confluence-global.bandana.xml` under your confluence-home directory as per the docs [here](https://developer.atlassian.com/docs/common-coding-tasks/storing-plugin-settings) and [here](https://developer.atlassian.com/confdev/development-resources/confluence-architecture/confluence-internals/persistence-in-confluence)
