### ISSUE TITLE
Wrong redirection after authentication 

### ISSUE THREAD

**Issue by yab86** [bitium/confluence-saml-plugin#73]
We are running on SAML Plugin version 1.0.5 and Confluence 5.9.9. The problem that we are facing is, that when a user enters a url of any confluence page and he is not already authenticated, he is redirected always to the dashboard. 

Example: User is not already authenticated:
1. User clicks https://<domain>.com/display/XX (existing space)
2. SAML authentication runs and after that, the users is redirected to https://<domain>.com instead of https://<domain>.com/display/XX

If the user is authenticated, it works prober. 

Is there something we can do to fix that issue?

Best regards and many thanks,
Yab86

**Comment by yab86** [comment]
Hi there

Any news or feedback here?

Best regards,
Yab86

**Comment by muchino** [comment]
We have the same question :)

**Comment by mohand3775** [comment]
Hi,

This plugin is dead no support no update no response for questions so big risk to take it.

**Comment by rkarodia** [comment]
We have scheduled updates to the Atlassian plugins at the beginning of April

**Comment by muchino** [comment]
Any updates on this?

**Comment by yab86** [comment]
deleting the values out of "Redirect URL" in the conf view solved the problem
